"""Leakage-controlled tools for the current-data provenance study.

The package keeps manifest discovery, split-controlled numerical loading, and
model evaluation separate.  In particular, development helpers cannot read a
record assigned to the locked split.
"""

from .core import (
    BASE_BATCH_SEED,
    CLASS_NAMES,
    CONSTRUCTED_BATCHES,
    DEVELOPMENT_BATCHES,
    EXPECTED_BANDS,
    EXPECTED_SOURCE_COUNTS,
    LOCKED_BATCHES,
    NUM_CLASSES,
    LockedDataAccessError,
    Manifest,
    MultiplicativeScatterCorrection,
    OOFDecisionResult,
    OOFProbabilityResult,
    SampleRecord,
    SavitzkyGolayTransformer,
    SpectralDataset,
    StandardNormalVariate,
    TemperatureCalibrationResult,
    build_sg15_logistic_regression,
    build_sg15_rbf_svm,
    build_sg15_shrinkage_lda,
    crossfit_oof_decision_temperature,
    decision_scores_to_probabilities,
    discover_manifest,
    equal_weight_probability_average,
    fit_decision_temperature,
    grouped_oof_decision_scores,
    grouped_oof_probabilities,
    load_csv_split,
    load_development_csv,
    load_locked_csv,
    multiclass_metrics,
    nested_grouped_oof_temperature_probabilities,
    sha256_file,
)

__all__ = [
    "BASE_BATCH_SEED",
    "CLASS_NAMES",
    "CONSTRUCTED_BATCHES",
    "DEVELOPMENT_BATCHES",
    "EXPECTED_BANDS",
    "EXPECTED_SOURCE_COUNTS",
    "LOCKED_BATCHES",
    "NUM_CLASSES",
    "LockedDataAccessError",
    "Manifest",
    "MultiplicativeScatterCorrection",
    "OOFDecisionResult",
    "OOFProbabilityResult",
    "SampleRecord",
    "SavitzkyGolayTransformer",
    "SpectralDataset",
    "StandardNormalVariate",
    "TemperatureCalibrationResult",
    "build_sg15_logistic_regression",
    "build_sg15_rbf_svm",
    "build_sg15_shrinkage_lda",
    "crossfit_oof_decision_temperature",
    "decision_scores_to_probabilities",
    "discover_manifest",
    "equal_weight_probability_average",
    "fit_decision_temperature",
    "grouped_oof_decision_scores",
    "grouped_oof_probabilities",
    "load_csv_split",
    "load_development_csv",
    "load_locked_csv",
    "multiclass_metrics",
    "nested_grouped_oof_temperature_probabilities",
    "sha256_file",
]
